# Generated by Django 4.1.3 on 2022-11-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0002_alter_links_options_remove_links_short_link_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short_links',
            new_name='ShortLinks',
        ),
    ]
