# Generated by Django 4.1.3 on 2022-11-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0003_rename_short_links_shortlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AddField(
            model_name='links',
            name='short_link',
            field=models.URLField(default=1, max_length=10, verbose_name='Short link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='unique_token',
            field=models.CharField(default=1, max_length=5, verbose_name='Unique token'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShortLinks',
        ),
    ]
