# Generated by Django 4.1.3 on 2022-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0004_alter_links_options_links_short_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='time_to_delete',
            field=models.DateTimeField(verbose_name='Time to delete'),
        ),
    ]
