# Generated by Django 4.1.3 on 2022-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0006_alter_links_time_to_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='short_link',
            field=models.URLField(max_length=30, verbose_name='Short link'),
        ),
    ]
