# Generated by Django 4.1.3 on 2022-12-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0007_alter_links_short_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount of visiting link')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='link_shortening.links')),
            ],
        ),
    ]
