# Generated by Django 4.1.3 on 2022-12-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0009_links_amount_delete_coanter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='amount of visiting link'),
        ),
    ]
