# Generated by Django 4.1.3 on 2022-12-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortening', '0010_alter_links_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount of visiting link'),
        ),
    ]
